name: PumpFun Scraper

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        run: node index.js

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scraped-tokens
          path: out.json
